# Copyright 2023 Logan Magee
#
# SPDX-License-Identifier: AGPL-3.0-only

name: Validate Gradle wrapper

on: [push, pull_request]

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
